/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [BusinessEntityID]
      ,[CountryRegionCode]
      ,[Name]
      ,[CurrencyCode]
      ,[Expr1]
      ,[DepartmentID]
      ,[GroupName]
      ,[ProductID]
      ,[LocationID]
      ,[Quantity]
      ,[ProductReviewID]
      ,[Rating]
  FROM [AdventureWorks2019].[dbo].[Example of Views]